version: 2

updates:
  - package-ecosystem: pip
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      python-development-dependencies:
        dependency-type: development
        patterns:
          - "*"
    labels:
      - dependencies
      - python

  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Europe/Paris
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
      - github-actions
